// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ucar/nc2/iosp/noaa/GhcnmIndex.proto

package ucar.nc2.iosp.noaa;

public final class GhcnmProto {
  private GhcnmProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface StationIndexOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StationIndex)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 stnid = 1;</code>
     */
    long getStnid();

    /**
     * <code>uint64 stnPos = 2;</code>
     */
    long getStnPos();

    /**
     * <code>uint64 dataPos = 3;</code>
     */
    long getDataPos();

    /**
     * <code>uint32 dataCount = 4;</code>
     */
    int getDataCount();
  }
  /**
   * Protobuf type {@code StationIndex}
   */
  public static final class StationIndex extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StationIndex)
      StationIndexOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use StationIndex.newBuilder() to construct.
    private StationIndex(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private StationIndex() {}

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new StationIndex();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private StationIndex(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              stnid_ = input.readUInt64();
              break;
            }
            case 16: {

              stnPos_ = input.readUInt64();
              break;
            }
            case 24: {

              dataPos_ = input.readUInt64();
              break;
            }
            case 32: {

              dataCount_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_StationIndex_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_StationIndex_fieldAccessorTable
          .ensureFieldAccessorsInitialized(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.class,
              ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder.class);
    }

    public static final int STNID_FIELD_NUMBER = 1;
    private long stnid_;

    /**
     * <code>uint64 stnid = 1;</code>
     */
    public long getStnid() {
      return stnid_;
    }

    public static final int STNPOS_FIELD_NUMBER = 2;
    private long stnPos_;

    /**
     * <code>uint64 stnPos = 2;</code>
     */
    public long getStnPos() {
      return stnPos_;
    }

    public static final int DATAPOS_FIELD_NUMBER = 3;
    private long dataPos_;

    /**
     * <code>uint64 dataPos = 3;</code>
     */
    public long getDataPos() {
      return dataPos_;
    }

    public static final int DATACOUNT_FIELD_NUMBER = 4;
    private int dataCount_;

    /**
     * <code>uint32 dataCount = 4;</code>
     */
    public int getDataCount() {
      return dataCount_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (stnid_ != 0L) {
        output.writeUInt64(1, stnid_);
      }
      if (stnPos_ != 0L) {
        output.writeUInt64(2, stnPos_);
      }
      if (dataPos_ != 0L) {
        output.writeUInt64(3, dataPos_);
      }
      if (dataCount_ != 0) {
        output.writeUInt32(4, dataCount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (stnid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeUInt64Size(1, stnid_);
      }
      if (stnPos_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeUInt64Size(2, stnPos_);
      }
      if (dataPos_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeUInt64Size(3, dataPos_);
      }
      if (dataCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(4, dataCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof ucar.nc2.iosp.noaa.GhcnmProto.StationIndex)) {
        return super.equals(obj);
      }
      ucar.nc2.iosp.noaa.GhcnmProto.StationIndex other = (ucar.nc2.iosp.noaa.GhcnmProto.StationIndex) obj;

      if (getStnid() != other.getStnid())
        return false;
      if (getStnPos() != other.getStnPos())
        return false;
      if (getDataPos() != other.getDataPos())
        return false;
      if (getDataCount() != other.getDataCount())
        return false;
      if (!unknownFields.equals(other.unknownFields))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STNID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getStnid());
      hash = (37 * hash) + STNPOS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getStnPos());
      hash = (37 * hash) + DATAPOS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getDataPos());
      hash = (37 * hash) + DATACOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getDataCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseDelimitedFrom(java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parseFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code StationIndex}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StationIndex)
        ucar.nc2.iosp.noaa.GhcnmProto.StationIndexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_StationIndex_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_StationIndex_fieldAccessorTable
            .ensureFieldAccessorsInitialized(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.class,
                ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder.class);
      }

      // Construct using ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        stnid_ = 0L;

        stnPos_ = 0L;

        dataPos_ = 0L;

        dataCount_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_StationIndex_descriptor;
      }

      @java.lang.Override
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex getDefaultInstanceForType() {
        return ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.getDefaultInstance();
      }

      @java.lang.Override
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex build() {
        ucar.nc2.iosp.noaa.GhcnmProto.StationIndex result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex buildPartial() {
        ucar.nc2.iosp.noaa.GhcnmProto.StationIndex result = new ucar.nc2.iosp.noaa.GhcnmProto.StationIndex(this);
        result.stnid_ = stnid_;
        result.stnPos_ = stnPos_;
        result.dataPos_ = dataPos_;
        result.dataCount_ = dataCount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ucar.nc2.iosp.noaa.GhcnmProto.StationIndex) {
          return mergeFrom((ucar.nc2.iosp.noaa.GhcnmProto.StationIndex) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex other) {
        if (other == ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.getDefaultInstance())
          return this;
        if (other.getStnid() != 0L) {
          setStnid(other.getStnid());
        }
        if (other.getStnPos() != 0L) {
          setStnPos(other.getStnPos());
        }
        if (other.getDataPos() != 0L) {
          setDataPos(other.getDataPos());
        }
        if (other.getDataCount() != 0) {
          setDataCount(other.getDataCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        ucar.nc2.iosp.noaa.GhcnmProto.StationIndex parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ucar.nc2.iosp.noaa.GhcnmProto.StationIndex) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long stnid_;

      /**
       * <code>uint64 stnid = 1;</code>
       */
      public long getStnid() {
        return stnid_;
      }

      /**
       * <code>uint64 stnid = 1;</code>
       */
      public Builder setStnid(long value) {

        stnid_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>uint64 stnid = 1;</code>
       */
      public Builder clearStnid() {

        stnid_ = 0L;
        onChanged();
        return this;
      }

      private long stnPos_;

      /**
       * <code>uint64 stnPos = 2;</code>
       */
      public long getStnPos() {
        return stnPos_;
      }

      /**
       * <code>uint64 stnPos = 2;</code>
       */
      public Builder setStnPos(long value) {

        stnPos_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>uint64 stnPos = 2;</code>
       */
      public Builder clearStnPos() {

        stnPos_ = 0L;
        onChanged();
        return this;
      }

      private long dataPos_;

      /**
       * <code>uint64 dataPos = 3;</code>
       */
      public long getDataPos() {
        return dataPos_;
      }

      /**
       * <code>uint64 dataPos = 3;</code>
       */
      public Builder setDataPos(long value) {

        dataPos_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>uint64 dataPos = 3;</code>
       */
      public Builder clearDataPos() {

        dataPos_ = 0L;
        onChanged();
        return this;
      }

      private int dataCount_;

      /**
       * <code>uint32 dataCount = 4;</code>
       */
      public int getDataCount() {
        return dataCount_;
      }

      /**
       * <code>uint32 dataCount = 4;</code>
       */
      public Builder setDataCount(int value) {

        dataCount_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>uint32 dataCount = 4;</code>
       */
      public Builder clearDataCount() {

        dataCount_ = 0;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StationIndex)
    }

    // @@protoc_insertion_point(class_scope:StationIndex)
    private static final ucar.nc2.iosp.noaa.GhcnmProto.StationIndex DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ucar.nc2.iosp.noaa.GhcnmProto.StationIndex();
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndex getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StationIndex> PARSER =
        new com.google.protobuf.AbstractParser<StationIndex>() {
          @java.lang.Override
          public StationIndex parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new StationIndex(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<StationIndex> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StationIndex> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StationIndexListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StationIndexList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .StationIndex list = 1;</code>
     */
    java.util.List<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex> getListList();

    /**
     * <code>repeated .StationIndex list = 1;</code>
     */
    ucar.nc2.iosp.noaa.GhcnmProto.StationIndex getList(int index);

    /**
     * <code>repeated .StationIndex list = 1;</code>
     */
    int getListCount();

    /**
     * <code>repeated .StationIndex list = 1;</code>
     */
    java.util.List<? extends ucar.nc2.iosp.noaa.GhcnmProto.StationIndexOrBuilder> getListOrBuilderList();

    /**
     * <code>repeated .StationIndex list = 1;</code>
     */
    ucar.nc2.iosp.noaa.GhcnmProto.StationIndexOrBuilder getListOrBuilder(int index);
  }
  /**
   * Protobuf type {@code StationIndexList}
   */
  public static final class StationIndexList extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StationIndexList)
      StationIndexListOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use StationIndexList.newBuilder() to construct.
    private StationIndexList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private StationIndexList() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new StationIndexList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private StationIndexList(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                list_ = new java.util.ArrayList<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readMessage(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_StationIndexList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_StationIndexList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.class,
              ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex> list_;

    /**
     * <code>repeated .StationIndex list = 1;</code>
     */
    public java.util.List<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex> getListList() {
      return list_;
    }

    /**
     * <code>repeated .StationIndex list = 1;</code>
     */
    public java.util.List<? extends ucar.nc2.iosp.noaa.GhcnmProto.StationIndexOrBuilder> getListOrBuilderList() {
      return list_;
    }

    /**
     * <code>repeated .StationIndex list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }

    /**
     * <code>repeated .StationIndex list = 1;</code>
     */
    public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex getList(int index) {
      return list_.get(index);
    }

    /**
     * <code>repeated .StationIndex list = 1;</code>
     */
    public ucar.nc2.iosp.noaa.GhcnmProto.StationIndexOrBuilder getListOrBuilder(int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList)) {
        return super.equals(obj);
      }
      ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList other = (ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList) obj;

      if (!getListList().equals(other.getListList()))
        return false;
      if (!unknownFields.equals(other.unknownFields))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseDelimitedFrom(java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parseFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code StationIndexList}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StationIndexList)
        ucar.nc2.iosp.noaa.GhcnmProto.StationIndexListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_StationIndexList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_StationIndexList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.class,
                ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.Builder.class);
      }

      // Construct using ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return ucar.nc2.iosp.noaa.GhcnmProto.internal_static_StationIndexList_descriptor;
      }

      @java.lang.Override
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList getDefaultInstanceForType() {
        return ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.getDefaultInstance();
      }

      @java.lang.Override
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList build() {
        ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList buildPartial() {
        ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList result =
            new ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList) {
          return mergeFrom((ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList other) {
        if (other == ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList.getDefaultInstance())
          return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ =
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ? getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.util.List<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex> list_ = java.util.Collections.emptyList();

      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          list_ = new java.util.ArrayList<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex>(list_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex, ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder, ucar.nc2.iosp.noaa.GhcnmProto.StationIndexOrBuilder> listBuilder_;

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public java.util.List<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public Builder setList(int index, ucar.nc2.iosp.noaa.GhcnmProto.StationIndex value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public Builder setList(int index, ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public Builder addList(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public Builder addList(int index, ucar.nc2.iosp.noaa.GhcnmProto.StationIndex value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public Builder addList(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public Builder addList(int index, ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public Builder addAllList(java.lang.Iterable<? extends ucar.nc2.iosp.noaa.GhcnmProto.StationIndex> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder getListBuilder(int index) {
        return getListFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndexOrBuilder getListOrBuilder(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public java.util.List<? extends ucar.nc2.iosp.noaa.GhcnmProto.StationIndexOrBuilder> getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.getDefaultInstance());
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder addListBuilder(int index) {
        return getListFieldBuilder().addBuilder(index, ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.getDefaultInstance());
      }

      /**
       * <code>repeated .StationIndex list = 1;</code>
       */
      public java.util.List<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder> getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex, ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder, ucar.nc2.iosp.noaa.GhcnmProto.StationIndexOrBuilder> getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ =
              new com.google.protobuf.RepeatedFieldBuilderV3<ucar.nc2.iosp.noaa.GhcnmProto.StationIndex, ucar.nc2.iosp.noaa.GhcnmProto.StationIndex.Builder, ucar.nc2.iosp.noaa.GhcnmProto.StationIndexOrBuilder>(
                  list_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      @java.lang.Override
      public final Builder setUnknownFields(com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StationIndexList)
    }

    // @@protoc_insertion_point(class_scope:StationIndexList)
    private static final ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList();
    }

    public static ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StationIndexList> PARSER =
        new com.google.protobuf.AbstractParser<StationIndexList>() {
          @java.lang.Override
          public StationIndexList parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new StationIndexList(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<StationIndexList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StationIndexList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ucar.nc2.iosp.noaa.GhcnmProto.StationIndexList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_StationIndex_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_StationIndex_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_StationIndexList_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_StationIndexList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData = {"\n#ucar/nc2/iosp/noaa/GhcnmIndex.proto\"Q\n"
        + "\014StationIndex\022\r\n\005stnid\030\001 \001(\004\022\016\n\006stnPos\030\002"
        + " \001(\004\022\017\n\007dataPos\030\003 \001(\004\022\021\n\tdataCount\030\004 \001(\r"
        + "\"/\n\020StationIndexList\022\033\n\004list\030\001 \003(\0132\r.Sta"
        + "tionIndexB \n\022ucar.nc2.iosp.noaaB\nGhcnmPr" + "otob\006proto3"};
    descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_StationIndex_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_StationIndex_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StationIndex_descriptor, new java.lang.String[] {"Stnid", "StnPos", "DataPos", "DataCount",});
    internal_static_StationIndexList_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_StationIndexList_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StationIndexList_descriptor, new java.lang.String[] {"List",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
