:source-highlighter: coderay
[[threddsDocs]]

= HTTP Services for netCDF-Java and Thredds

Created: July 20, 2011 +
Revised: Sept. 18, 2019

:toc:

== Introduction

NetCDF-Java clients currently use the https://hc.apache.org/[Apache
HttpClient Libraries] for communicating with remote servers to obtain
data. Unfortunately, these libraries are under continuous development,
so their APIs are unstable from version to version. In addition, as of
httpclient version 4.3, the libraries have moved to an immutable object
model that makes using them complicated to use.

In order to provide some API stability and to simplify common use, the
Apache libraries have been wrapped. The wrapping code is in the
_ucar.httpservices_ package. The new public classes are:
__HTTPFactory.java__, __HTTPFormBuilder.java__, __HTTPSession.java__,
__HTTPMethod.java__, __HTTPMethodStream.java__, __HTTPCredentialsProvider__,
and __HTTPException.java__. Additionally, the class
_ucar.nc2.util.net.HttpClientManager_ is closely tied to the
_ucar.httpservices_ package.

This document describes _some_ of the methods for each class. For a
complete description of the API, the javadoc files should be referenced.

Note that when the code was switched to using httpclient version 4.5,
the API was changed somewhat to reflect experience with previous
versions. Some methods exist to support Backward compatibility, but are
deprecated. When netcdf-java was split from Thredds, additional
changes were made. When the switch to the Java httpclient module
occurs, additional, major, changes can be expected.

=== HTTPSession and Session Semantics

These class _HTTPSession_ supports a form of _session_ semantics for
Java network access. The notion of session is loosely tied to the HTTP
notion of session. Specifically, an instance of _HTTPSession_ defines a
scope within which authentication and Http methods (e.g. put, get)
operate.

The primary key for an _HTTPsession_ object is an instance of
__AuthScope__, which consists of a host (an ip address or name such as
unidata.ucar.edu), a port number, and an authorization scheme
(e.g. ''Basic'' or ''NTLM).

Effectively, an _AuthScope_ is intended to map to a specific server
somewhere in the internet. Authentication information (credentials) are
tied to that scope and all http methods (put, get, etc.) operate in the
context of an __AuthScope__.

Notes:

* It is possible to convert a URL to an _AuthScope_ by taking just the
hostname and port of the URL and ignoring the rest.
* Once set, it is not possible to change the _AuthScope_ for an
_HTTPSession_ object: it is immutable in this respect.
* _HTTPSession_ objects do NOT necessarily correspond to the Http notion
of a session (SESSIONID or JSESSIONID). There are security issues
involved with using SESSIONID that have not yet been resolved.
* It is impossible to create an _HTTPSession_ object without specifying
an __AuthScope__.

==== HTTPSession API

The primary _HTTPSession_ methods of interest are divided into two
groups: global and instance. The global methods are static methods of
_HTTPSession_ and allow operations that will apply to all instances of
__HTTPSession__, unless specifically overridden. The instance methods,
as a rule, parallel the global methods, but apply only to a specific
session instance. Some methods can only be specified globally or
per-instance.

The non authentication related global methods of general interest are as
follows.

* `static public void setGlobalUserAgent(String userAgent)`
* `static public void setGlobalCompression(String compressors)`
   + As a rule, the only allowable compressors are ''gzip'' and ''deflate''.
* `static public void setMaxRedirects(int n)`
* `static public void setFollowRedirects(boolean tf)`

The non authentication related per-instance methods of general instance
are as follows.

* `public void close()`
   + _HTTPSession_ is AutoCloseable so try-with-resources can be used.
* `public void setCompression(String compressors)`
* `public void removeCompression()`
* `public void setUserAgent(String agent)`
* `public void setMaxRedirects(int n)`
* `public void setFollowRedirects(boolean tf)`
* `public void clearCookies()`
* `public List getCookies()` ``

As of the netcdf-java split, a number of deprecated method
have been removed. These are no longer detailed here.

==== Authentication-Related HTTPSession Methods

The key objects for authentication are the classes
_org.apache.http.client.CredentialsProvider_ and
__org.apache.http.client.Credentials__. Basically, when an instance of
__CredentialsProvider__'s _getCredentials_ method is invoked, it is
expected to return and instance of __Credentials__. The two are
distinguished because _Credentials_ is immutable, while
_CredentialsProvider_ can return a different set of _Credentials_ every
time it is invoked. 

It is important to understand that a __CredentialsProvider__ object
_caches_ a set of credentials. The credentials are keyed with an
__AuthScope__ object, so when _getCredentials_ is called with an
__AuthScope__ argument, the provider is expected to return the credentials
that correspond to that __AuthScope__. Note that here, correspondence
is not equality, but rather the auth scope argument is used to find
the "closest" auth scope in the cache and that is used to choose
the credentials. Caching is also important when
a client repeatedly accesses the same dataset, it will be asked for the
username+password only once because the corresponding credentials
were cached. For an example, one can look at
the file __UrlAuthenticatorDialog.java__.

To elaborate, consider the case where we want to access a number of
datasets on a server, where each dataset might be protected by some
combination of username+password. This is often called BASIC
authentication. When a request is made for one of these datasets, the
_CredentialsProvider_ is invoked and it may do something like pop up a
window to ask the user for the needed username+password for this
dataset. When another dataset is accessed, it may pop up another window
if the __AuthScope__ argument for that dataset differs.
Thus the same _CredentialsProvider_ may be used repeatedly. In each
case, it would return a specific instance of _Credentials_ that contains
the requisite username+password for that specific __AuthScope__.

As of the netcdf-java split, HTTPSession only takes __CredentialsProvider__
arguments. It no longer supports __Credentials__ arguments. This means
that the user may have to use the __CredentialsProvider__._setCredentials_
method to pre-store specific credentials into a provider.

* ``
static public void setGlobalCredentialsProvider(CredentialsProvider provider) throws HTTPException ``
* ``
public void setCredentialsProvider(CredentialsProvider provider) throws HTTPException ``


==== SSL HTTPSession Methods

SSL support has changed significantly since Apache httpclient 4.5.
It is expected that this is controlled using the jvm -D flags.

Relevant SSL related values can
be specified on the java VM command line using the following JVM
parameters.

* ''-Dkeystore=...''
* ''-Dkeystorepassword=...''
* ''-Dtruststore=...''
* ''-Dtruststorepassword=...''

==== Proxy Support

Proxy support is also expected to be set up using jvm -D flags.

* ''-Dproxyurl=...''

This flag is a URL that specifies the proxy.

Notes:

* The path, query, and fragment parts of the URL are ignored.
* If the proxy needs authentication, then the URL needs to include it in
the form of ''http(s)://username:password@host:port''.

=== HTTPMethod

This class encapsulates the information about a given method request and
response. Its primary operation is __execute()__, which causes a request
to be sent to a server and a response obtained.

An instance of _HTTPMethod_ always operates in the context of a parent
_HTTPSession_ object. It is possible to create an _HTTPMethod_ object
without specifying a parent session object. In that case, a temporary
_HTTPSession_ object is created by the method object. The lifetime of
the session object is the same as the method object: that is, when the
method object is closed, the temporary session object will also be
closed.

_HTTPMethod_ takes a URL string as its primary argument. Optionally (but
normally), it may take an _HTTPSession_ object as an additional
argument. Alternatively, one can give only the session as the sole argument,
in which case the url of the session is used as the method url.

An important point about the URL argument is that it must be
*compatible* with the _AuthScope_ of the parent _HTTPSession_ object.
The term ''compatible'' means the following. The method url is compatible
if the URL's host+port is the same as the session scope's host+port.

=== HTTPMethodStream

This class is a subclass of __java.io.InputStream__. Its purpose is to
allow other classes to access the data stream associated with a method
response. It is often convenient to get data using an _HTTPMethod_
instance in a Java scope, but then pass the associated input stream out
of scope. When the stream is closed (or hits EOF) somewhere else in the
code, it is desirable that the associated method and its resources be
closed automatically.

=== HTTPException

This class is a subclass of __java.io.IOException__. It is the exception
for reporting errors out of the _ucar.httpservices_ package.

=== HTTPFactory

The _HTTPFactory_ conveniance class provides the API for
obtaining instances of an HTTPSession or HTTPMethod object.

For session creation, the following methods are provided:

* ``
static public HTTPSession newSession(String host, int port) throws HTTPException ``
* ``
static public HTTPSession newSession(String url) throws HTTPException ``
* ``
static public HTTPSession newSession(HttpHost target) throws HTTPException ``

The idea is that the argument(s) are sufficient to extract a usable
host+port.

For method creation, the supported methods are: GET, HEAD, PUT, POST,
and OPTIONS. For each method Xxx (e.g. Get, Put, etc), the following
factory methods are provided.

* ``
static public HTTPMethod Xxx(HTTPSession session, String url) throws HTTPException ``
* ``
static public HTTPMethod Xxx(String url) throws HTTPException ``
* ``
static public HTTPMethod Xxx(HTTPSession session) throws HTTPException ``

As described above, if the session is not explicit, then a temporary
session object will be created with the _AuthScope_ taken from the url.
Also, if the session is explicit, then the url argument must be
compatible with the session's __AuthScope__. If the url is not specified,
then the url used to create the parent session is used.

=== ucar.nc2.util.net.HttpClientManager

This class is a utility class to perform some specialized actions. Its
name begins with ''Http'' rather than ''HTTP'' for historical reasons. It
has been extensively modified internally to utilize the
_ucar.httpservices_ package.

This class contains only static methods and these methods perform the
following utility operations.

* `String getUrlContentsAsString(String urlencoded, int maxKbytes)` +
  Return the contents of a URL as a String; makes a request on the specified url and return its response as a String of max length __maxKbytes__.
* `void copyUrlContentsToFile(String urlencoded, File file) throws HTTPException` +
  Get the contents of URL and store in a file; makes a request on the specified url, obtain its contents and write to the specified file.
* `long appendUrlContentsToFile(String url, File file, long start, long end)` +
  Append the contents of a URL to the end of a File; makes a request on the specified url, obtain its contents and append to the specified file.
* `void init(CredentialsProvider provider, String userAgent)` +
  Initialize the Client Manager class to use a specified credentials provider and user agent when making requests.

=== Examples

==== Example 1: Create/Use/Release Cycle

This example uses try-with-resources instead of explicit calls to the
close methods.
....
public class Main
{
    public static void main(String[] argv)
    {
        String url = argv[0];
        try (HTTPSession session = new HTTPSession(url);
             HTTPMethod method = HTTPMethod.Get(session,url);
             int status = method.execute();
             System.out.printf("Execute: status code = %d\n", status);
        } // implicitly calls method.close() then session.close()
    }
}
....

==== Example 2: Using HttpClientManager
....
public class Main
{
    public static void main(String[] argv)
    {
        String url = argv[0[];
        string content = HttpClientManager.getUrlContentsAsString(url,1024);
    }
}
....

==== Example 3: Setting Some Global Parameters

This example set some global parameters and also shows the use of an
implicit session.
....
public class Main
{
    public static void main(String[] argv)
    {
        String url = argv[0];
        String userpwd = argv[1];

        // Set some parameters at the global level
        BasicCredentialsProvider bcp = new BasicCredentialsProvider();
        bcp.setCredentials(new UsernamePasswordCredentials(userpwd));
        HTTPSession.setGlobalCredentialsProvider(bcp);
        HTTPSession.setGlobalUserAgent("netcdf/java");
        HTTPSession.setMaxConnections(4);
        HTTPSession.setGlobalAuthenticationPreemptive(true);

        try (HTTPMethod method = HTTPMethod.Get(url)) {//implicit session
            int status = method.execute();
            System.out.printf("Execute: status code = %d\n", status);
        }
    }
}
....

==== Example 4: Setting Some Local Parameters
Note the use of a fluent/chained interface.
....
public class Main
{
    public static void main(String[] argv)
    {
        String url = argv[0];
        String userpwd = argv[1];

        try (HTTPSession session = new HTTPSession(url)) {
            BasicCredentialsProvider bcp = new BasicCredentialsProvider();
            bcp.setCredentials(new UsernamePasswordCredentials(userpwd));
            session.setCredentialsProvider(bcp);
            session.setUserAgent("agent")
                   .setConnectionManagerTimeout(475);
                   .setSoTimeout(475);
            try (HTTPMethod method = HTTPMethod.Get(session)) {
                int status = method.execute();
                System.out.printf(''Execute: status code = %d\n'', status);
            } // method.close()
        } // session.close()
    }
}
....

== Appendices

=== Appendix A: AuthScope

The
https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/auth/AuthScope.html[AuthScope]
class is used in a number of places in the _ucar.httpservices_ package.
It has a number of constructors, the only usable one is as follows.

* ``
AuthScope(String hostname, int port) ``

[[author]]
Author
~~~~~~

Author: Dennis Heimbigner
+ Affiliation: UCAR/Unidata
+  email: dmh@ucar.edu

