/*
 * Copyright (c) 1998-2021 John Caron and University Corporation for Atmospheric Research/Unidata
 * See LICENSE for license information.
 */

/**
 * <pre>
 * DEPRECATED API - THIS AND ALL SUBPACKAGES WILL BE REPLACED / MOVE
 * </pre>
 * <ul>
 * <li>CdmRemote: A remote CDM dataset (extending NetcdfFile), using cdmremote protocol to communicate</li>
 * <li>NcStream: encoding and decoding the protobuf messages</li>
 * <li>ncStream.proto: defines the protobuf messages</li>
 * <li>NcStreamProto: generated by probuf compiler</li>
 * <li>NcStreamReader: Read an ncStream InputStream into a NetcdfFile (used by CdmRemote)</li>
 * <li>NcStreamWriter: Write a NetcdfFile to an OutputStream using ncstream protocol</li>
 * <li>NcStreamWriterChannel: Write a NetcdfFile to an WritableByteChannel using ncstream protocol</li>
 * <li>NcStreamIosp: IOSP to read an ncStream that has been written to a file</li>
 * </ul>
 */
package ucar.nc2.stream;
