on:
  pull_request:

permissions:
  contents: read

jobs:
  netcdf-java-tests:
    name: netCDF-Java Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest 8, 11, 17, 21 of zulu and temurin java
        java-version: [8, 11, 17, 21, 25]
        java-vendor: ['temurin', 'corretto']
    steps:
      - uses: actions/checkout@v6
      - name: Build with ${{ matrix.java-vendor }} 17 and run tests with ${{ matrix.java-vendor }} 8
        if: ${{ matrix.java-version == 8 }}
        uses: Unidata/thredds-test-action@v4
        with:
          java-vendor: ${{ matrix.java-vendor }}
          java-version: 17
          build-tool: 'gradlew'
          test-command: '-Dorg.gradle.java.installations.fromEnv=TEST_JDK --info --stacktrace test'
        env:
          TEST_JDK: /usr/thredds-test-environment/${{ matrix.java-vendor }}8
      - name: Build with ${{ matrix.java-vendor }} 17 and run tests with ${{ matrix.java-vendor }} ${{ matrix.java-version }}
        if: ${{ matrix.java-version != 8 }}
        uses: Unidata/thredds-test-action@v4
        with:
          java-vendor: ${{ matrix.java-vendor }}
          java-version: 17
          build-tool: 'gradlew'
          test-command: '-Dorg.gradle.java.installations.fromEnv=TEST_JDK --info --stacktrace testWithJdk${{ matrix.java-version }}'
        env:
          TEST_JDK: /usr/thredds-test-environment/${{ matrix.java-vendor }}${{ matrix.java-version }}
      - name: Cleanup build-logic-ncj build directory
        if: failure()
        run: sudo rm -rf build-logic-ncj/build/
      - uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: netCDF-Java_JUnit_Results_${{ github.sha }}_${{ matrix.java-vendor }}-${{ matrix.java-version }}
          path: ${{ github.workspace }}/**/build/reports/*
